CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    status     VARCHAR(20)  NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED')),
    author_id  BIGINT       NOT NULL REFERENCES users (id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE post_tags (
    post_id BIGINT       NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag     VARCHAR(255) NOT NULL
);

CREATE INDEX idx_post_tags_post_id ON post_tags (post_id);
