spring.application.name=blog-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_admin
spring.datasource.username=blog
spring.datasource.password=blog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
